apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gcrcbn
  annotations:
    run.googleapis.com/minScale: '2'
spec:
  template:
    spec:
      serviceAccountName: qa-automation-deployment-token@qa-target.iam.gserviceaccount.com
      containers:
        - image: <image>
          ports:
            - containerPort: 8080
              name: http1
